/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright (c) Neosyn. C⏚ ("C-Ground") is the open-source continuation
 * of the Synflow Cx toolchain, originally developed by Synflow.
 */

package com.neosyn.cg.tests.codegen;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.concurrent.TimeUnit;

import org.junit.Assume;
import org.junit.Test;

/**
 * Drift-detection test for IR generation.
 *
 * IR is generated by two parallel code paths that have drifted silently in the
 * past (see {@code memory/feedback_parallel_code_paths.md}):
 *
 * <ul>
 *   <li>{@code com.neosyn.cg.generator.CgGenerator} (Eclipse / Xtext
 *       {@code doGenerate}) — exercised by {@code mvn verify} on
 *       {@code com.neosyn.cg.tests}.
 *   <li>{@code com.neosyn.cg.ide.server.TransformationHandler} (LSP) —
 *       exercised by VS Code Fast Sim and the
 *       {@code cg-language-server.jar generate-ir} CLI.
 * </ul>
 *
 * Mechanism: {@link GoldenFileTests#testIR_GoldenSimple_Counter()} already
 * verifies that the Eclipse-path output matches the committed
 * {@code tests/golden/ir/Counter.ir}. This test invokes the LSP path via the
 * standalone server jar and asserts that its output also matches the same
 * golden. If both paths match, IR generation is consistent across them. If the
 * LSP output drifts, this test fails and points the developer at the
 * parallel-code-paths note.
 *
 * The test is skipped (via {@link Assume}) when the LSP jar is not built, so
 * a fresh checkout that has not yet run {@code mvn package -pl releng/lsp-server}
 * does not produce a spurious red.
 */
public class IrPathDriftTests {

	private static final String FIXTURE_REL = "tests/golden/GoldenSimple.cg";
	private static final String GOLDEN_IR_REL = "tests/golden/ir/Counter.ir";
	private static final String LSP_IR_REL = ".ir/com/neosyn/test/golden/Counter.ir";

	@Test
	public void drift_GoldenSimple_Counter_LspMatchesEclipseGolden() throws Exception {
		Path workspaceRoot = findWorkspaceRoot();
		Path lspJar = workspaceRoot.resolve("releng/lsp-server/target/cg-language-server.jar");
		Assume.assumeTrue(
				"LSP jar not built at " + lspJar + "; run `mvn package -pl releng/lsp-server` first",
				Files.isRegularFile(lspJar));

		Path testsPlugin = workspaceRoot.resolve("plugins/com.neosyn.cg.tests");
		Path fixture = testsPlugin.resolve(FIXTURE_REL);
		Path goldenIr = testsPlugin.resolve(GOLDEN_IR_REL);
		Path lspIr = testsPlugin.resolve(LSP_IR_REL);

		assertTrue("Fixture missing: " + fixture, Files.isRegularFile(fixture));
		assertTrue("Eclipse-path golden missing: " + goldenIr, Files.isRegularFile(goldenIr));

		Files.deleteIfExists(lspIr);
		runLspGenerateIr(lspJar, fixture);

		if (!Files.isRegularFile(lspIr)) {
			fail("LSP generate-ir produced no IR file at " + lspIr);
		}

		String lspText = readUtf8(lspIr);
		String goldenText = readUtf8(goldenIr);

		assertEquals(
				"IR-path drift detected: cg-language-server.jar generate-ir produced "
						+ "an IR for com.neosyn.test.golden.Counter that does NOT match the "
						+ "Eclipse-path golden at " + GOLDEN_IR_REL + ". "
						+ "See memory/feedback_parallel_code_paths.md — the two paths have "
						+ "diverged. Grep both com.neosyn.cg/generator/ and "
						+ "com.neosyn.cg.ui/ide/server/ for the relevant transformation.",
				goldenText, lspText);
	}

	private static Path findWorkspaceRoot() {
		Path cwd = Paths.get("").toAbsolutePath();
		for (Path candidate = cwd; candidate != null; candidate = candidate.getParent()) {
			if (Files.isDirectory(candidate.resolve("plugins/com.neosyn.cg.tests"))
					&& Files.isDirectory(candidate.resolve("releng"))) {
				return candidate;
			}
		}
		throw new IllegalStateException(
				"Could not locate neosyn-studio workspace root from " + cwd);
	}

	private static void runLspGenerateIr(Path lspJar, Path fixture)
			throws IOException, InterruptedException {
		ProcessBuilder pb = new ProcessBuilder(
				"java", "-jar", lspJar.toString(),
				"generate-ir", fixture.toAbsolutePath().toString());
		pb.environment().put("NEOSYN_CG_DEV", "1");
		pb.redirectErrorStream(true);
		Process p = pb.start();
		boolean done = p.waitFor(120, TimeUnit.SECONDS);
		if (!done) {
			p.destroyForcibly();
			fail("LSP generate-ir timed out after 120s");
		}
		if (p.exitValue() != 0) {
			String out = new String(p.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
			fail("LSP generate-ir exited with code " + p.exitValue() + ":\n" + out);
		}
	}

	private static String readUtf8(Path path) throws IOException {
		return new String(Files.readAllBytes(path), StandardCharsets.UTF_8);
	}
}
