/*******************************************************************************
 * Originally developed by Synflow until February 2021 under LGPL. Now maintained by Neosyn team since January 2024.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:


 *******************************************************************************/
package com.neosyn.test.app.basics;

network CustomTestbench {

	in sync u8 a, sync b, sync c; out sync u10 res;

	sum = new task {
		void loop() {
			res.write(a.read + b.read + c.read); 
		}
	};

}
