/*******************************************************************************
 * Originally developed by Synflow until February 2021 under LGPL. Now maintained by Neosyn team since January 2024.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:


 *******************************************************************************/
package com.neosyn.test.app.inner;

network Inner {

  properties {
    test: {
      even:    [    0, null,    2, null,    4, null, null ],
      odd:     [ null,    1, null,    3, null,    5, null ],
      numbers: [ null,    0,    1,    2,    3,    4,    5 ]
    }
  }

  in u8 even, odd; out u8 numbers;

  evenTask = new Copy();
  evenTask.reads(even);

  oddTask = new Copy();
  oddTask.reads(odd);

  joinEvenOdd = new task {
    void setup() {
      // waits for one cycle initially
      idle(1);
    }

    void loop() {
      numbers.write(evenTask.dout.read());
      numbers.write(oddTask.dout.read());
    }
  };

}

task Copy {
  in u8 din; out u8 dout;
  void loop() {
    dout.write(din.read());
  }
}
