/*
 * generated by Xtext 2.34.0
 */
package com.neosyn.cg.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CgUiModule extends AbstractCgUiModule {

	public CgUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
