/*
 * generated by Xtext 2.16.0
 */
package com.neosyn.cg.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.neosyn.cg.CgRuntimeModule;
import com.neosyn.cg.CgStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CgIdeSetup extends CgStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CgRuntimeModule(), new CgIdeModule()));
	}
	
}
