/*
 * generated by Xtext 2.16.0
 */
package com.neosyn.cg.ide;

import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.ide.editor.folding.IFoldingRangeProvider;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2;
import org.eclipse.xtext.ide.server.hover.IHoverService;

import com.neosyn.cg.ide.generator.CgNoOpGenerator;
import com.neosyn.cg.ide.server.CgCodeActionService;
import com.neosyn.cg.ide.server.CgFoldingRangeProvider;
import com.neosyn.cg.ide.server.CgHoverService;
import com.neosyn.cg.ide.server.CgSemanticHighlightingCalculator;

/**
 * Use this class to register ide components.
 *
 * For standalone/LSP mode, we override the generator binding to use a no-op
 * implementation that doesn't depend on Eclipse workspace APIs.
 */
public class CgIdeModule extends AbstractCgIdeModule {

    /**
     * Bind a no-op generator for standalone/LSP mode.
     *
     * The real CgGenerator depends on Eclipse workspace APIs (ResourcesPlugin)
     * which are not available in standalone mode.
     */
    public Class<? extends IGenerator> bindIGenerator() {
        return CgNoOpGenerator.class;
    }

    /**
     * Bind the C⏚-aware hover service that produces rich markdown for ports,
     * tasks, networks, bundles, and instances.
     */
    public Class<? extends IHoverService> bindIHoverService() {
        return CgHoverService.class;
    }

    /**
     * Bind the C⏚-aware folding-range provider that folds structural blocks
     * (task/network/bundle/struct/enum bodies and statement blocks) instead of
     * the default's every-multi-line-node behavior. See CgFoldingRangeProvider.
     */
    public Class<? extends IFoldingRangeProvider> bindIFoldingRangeProvider() {
        return CgFoldingRangeProvider.class;
    }

    /**
     * Bind the C⏚ code-action service (deprecated interface-keyword migration).
     * Binding the service is what makes Xtext advertise codeActionProvider.
     */
    public Class<? extends ICodeActionService2> bindICodeActionService2() {
        return CgCodeActionService.class;
    }

    /**
     * Bind the C⏚ semantic-highlighting calculator (ports → property, entity
     * names → type, enum literals → enumMember). Overrides the no-op default.
     */
    public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
        return CgSemanticHighlightingCalculator.class;
    }
}
